### ISSUE TITLE
Update Fisher to version 4

### ISSUE THREAD

**Issue by edouard-lopez** [andreiborisov/docker-fish#2]
### Image

```
❯ docker pull andreiborisov/fish:3.1.2
3.1.2: Pulling from andreiborisov/fish
Digest: sha256:df344b6af8dc1b3d7a87b80eec7240db9097a1f72463e93ad07fc57db5b01eb2
Status: Image is up to date for andreiborisov/fish:3.1.2
docker.io/andreiborisov/fish:3.1.2
```

### Fisher version
```
❯ docker run --rm --interactive --tty andreiborisov/fish:3.1.2 'fisher --version'
fisher version 3.3.2 ~/.config/fish/functions/fisher.fish
```

This is a bit annoying for `pure` as the code and doc assume v4. I added a [small function](https://github.com/rafaelrinaldi/pure/blob/55bef050159bc9d56d62fb9362d9b6f4e05ec526/tools/versions-compare.fish#L42-L46) to manage that case in the [installer tests](https://github.com/rafaelrinaldi/pure/blob/55bef050159bc9d56d62fb9362d9b6f4e05ec526/tests/pure_tools_installer.test.fish#L151-L168)

**Comment by andreiborisov** [comment]
I was going to fix this along with other stuff, but if this is an issue for you, I'll make this a priority. Thanks!
